### ISSUE TITLE
Response from types call returns only name and types codename

### ISSUE THREAD

**Issue by Simply007** [Enngage/KenticoCloudDeliveryTypeScriptSDK#16]
I have used delivery client to load content type definition.
I have needed to get all possible options from the multiple choice field.

I have used the code defined in:
https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK#working-with-content-types

Response does not contain possible options to the multi choice field:
![multiplechoice](https://user-images.githubusercontent.com/9218736/29712606-01a2242a-899b-11e7-85f4-a10735626161.png)

There is also no raw response that could be used to get the option values.

Note it would be also good to extend type calling by specifik what elements to load, but it does not block me :-)
https://developer.kenticocloud.com/v1/reference#view-a-content-type-element

**Comment by Enngage** [comment]
Strongly typed support for options is added in https://github.com/Enngage/KenticoCloudDeliveryTypeScriptSDK/releases/tag/v1.5.12 

Try updating NPM version and let me know if this works as you need :-)

I'll add support for querying only certain elements in future releases since I have no time now :/
