### ISSUE TITLE
Possibility to set base url for api calls

### ISSUE THREAD

**Issue by Journerist** [Enngage/KenticoCloudDeliveryTypeScriptSDK#34]
Hi,

is there a way to set the base url for accessing kentico cloud? I would like to proxy all calls to protect sensitive data. Is there are global config parameter available?

If not can you please add a configuration?

Instead of calling:
https://preview-deliver.kenticocloud.com/{key}/items?system.type=article

it should call:
https://{custom url}/items?system.type=article

when set.

**Comment by edouardr** [comment]
The urls for delivery and preview API are set in the QueryService class as `private readonly` attributs.

What about exposing them in the DeliveryClientConfig class? QueryService is already instantiated with the config object.

**Comment by Journerist** [comment]
Sounds Good for me. Looking forward to an implementation and documentation ;).

**Comment by petrsvihlik** [comment]
See how it's implemented in the .net sdk for reference.

**Comment by Journerist** [comment]
alright, so what do you mean by that? Do you ask me to contribute ? Or will you do/delegate it?

I'm open minded in this case :).

**Comment by petrsvihlik** [comment]
@Journerist sorry for confusion, it was rather a generic remark, not addressed to anyone in particular :)

It would be great if you could take care of it.

So what we did in the .NET SDK is that we introduced a [`DeliveryOptions`](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/Configuration/DeliveryOptions%20.cs) object, adjusted DeliveryClient's [constructors](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/DeliveryClient.cs#L149). And here's an example of how it can be used: https://github.com/Kentico/delivery-sdk-net/wiki/Using-the-ASP.NET-Core-Configuration-API-and-DI-to-Instantiate-the-DeliveryClient.

I'm not saying we should do it the exactly same thing but the general look&feel should be somewhat similar :)

Please let us know if you're willing to contribute so that we can assign the issue to you.

**Comment by Enngage** [comment]
Hey guys, 

This is a good idea. I implemented it so that you can specify base urls when instantiating `DeliveryClientConfig`. I published it in `2.1.2` release:

```
new DeliveryClientConfig('projectId', [], {
      baseUrl: 'http://customurl.com',
      basePreviewUrl: 'http://custompreview.com'
    });
```

Let me know how that works and if you have any further suggestions.

**Comment by Journerist** [comment]
@Enngage thank you, this is awesome. I'll try it this evening and give you feedback if this works for me.

**Comment by Journerist** [comment]
I already love it, works amazingly. Finally I can get rid of my ugly hack :P. Thanks a lot ! <3
