### ISSUE TITLE
API Call appears to go out twice

### ISSUE THREAD

**Issue by ChristopherJennings** [Enngage/KenticoCloudDeliveryTypeScriptSDK#7]
I've noticed that it appears that the client makes the API calls twice. The first call goes out, doesn't complete and then the second call goes out and then completes like it should. This is the behavior in my React app as well as the [simple sample javascript app](https://github.com/Enngage/KenticoCloudSampleJavascriptApp).

**Comment by Enngage** [comment]
According to my knowledge, this is the correct behavior managed by browser automatically when dealing with requests across multiple domains (CORS) as explained [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) or [https://stackoverflow.com/questions/29954037/how-to-disable-options-request](here)

The request is used with OPTIONS also if we use different content type then the following:

application/x-www-form-urlencoded
multipart/form-data
text/plain

And since we use application/json, we won't be able to get rid of this.

PS: Both [Kentico advantage](http://advantage.kentico.com) & [Kentico Cloud app](https://app.kenticocloud.com) have the same behavior for e.g. Hotjar that is included.

**Comment by ChristopherJennings** [comment]
Ah, you are 100% correct. I missed that the first request was an options request method. Thanks for clarifying.
